"""
Agent state definition for the LangGraph graph.

``AgentState`` is the single mutable object threaded through every node in the
graph. Nodes read from it to get their inputs and write back to it to pass
outputs to the next node. LangGraph snapshots it between nodes for free
replay and inspection.

All nullable fields are typed ``X | None`` and start as ``None`` — they are
populated progressively as the graph advances.  All fields are always present
in the dict (``total=True``); ``None`` signals "not yet set", not "absent".

``AgentStatus`` is exported separately so other modules (graph edges, API
response mappers) can reference the valid status strings without importing
the full state.

Usage::

    from agent.state import AgentState, AgentStatus
    from agent.tracing import Tracer

    state: AgentState = {
        "question":             "Who teaches Algorithms?",
        "schema_context":       schema_str,
        "sql":                  None,
        "sql_error":            None,
        "retry_count":          0,
        "db_results":           None,
        "answer":               None,
        "status":               "analyzing",
        "conversation_history": history,
        "accumulated_intent":   None,
        "last_clarification":   None,
        "ambiguity_count":      0,
        "trace_id":             trace_id,
        "session_id":           session_id,
        "tracer":               tracer,
    }

Settings used:
    MAX_SQL_RETRIES             -- upper bound for ``retry_count``
    MAX_CLARIFICATION_ROUNDS    -- upper bound for ``ambiguity_count``
    CONVERSATION_HISTORY_WINDOW -- max length of ``conversation_history``
    (limits are enforced by the nodes that increment these counters, not here)
"""

from typing import Literal, TypedDict

from agent.tracing import Tracer

AgentStatus = Literal[
    "analyzing",
    "generating",
    "validating",
    "executing",
    "formatting",
    "asking_clarification",
    "error",
    "done",
]
"""All valid values for ``AgentState["status"]``."""


class AgentState(TypedDict):
    """
    Shared state passed between every node in the agent graph.

    Fields are grouped into three concerns:

    **Core** — the question being answered and the SQL pipeline state.

    **Multi-turn** — conversation history and clarification tracking that
    persist across turns of the same session.

    **Tracing** — identifiers and the ``Tracer`` instance used for
    structured logging throughout the graph run.
    """

    # ------------------------------------------------------------------
    # Core
    # ------------------------------------------------------------------

    question: str
    """The raw user question for the current turn."""

    schema_context: str
    """Pre-built prompt-ready schema string injected from the DB at startup."""

    sql: str | None
    """The SQL statement generated by ``sql_generator``; None before that node runs."""

    sql_error: str | None
    """Error message from the last failed ``sql_executor`` attempt; None on success."""

    retry_count: int
    """Number of SQL generation retries attempted so far for the current question."""

    db_results: list[dict] | None
    """Rows returned by ``sql_executor``; None until execution succeeds."""

    answer: str | None
    """Natural-language answer produced by ``answer_formatter``; None until formatting."""

    status: AgentStatus
    """Current pipeline stage; drives graph routing between nodes."""

    # ------------------------------------------------------------------
    # Multi-turn
    # ------------------------------------------------------------------

    conversation_history: list[dict]
    """Recent turns as ``[{"role": "user"|"assistant", "content": "..."}, ...]``.
    Capped to ``CONVERSATION_HISTORY_WINDOW`` turns by the API layer."""

    accumulated_intent: str | None
    """Merged user intent built up across clarification rounds.
    Grows each turn until the question is resolved; reset to None on a fresh question."""

    last_clarification: str | None
    """The clarification question the agent asked in the previous turn.
    Set by ``question_analyzer`` when routing to ``asking_clarification``;
    used on the next turn to trigger intent merging."""

    ambiguity_count: int
    """Number of clarification rounds for the current question.
    Incremented each time the agent asks a clarification; reset to 0 on resolution."""

    # ------------------------------------------------------------------
    # Tracing
    # ------------------------------------------------------------------

    trace_id: str
    """Unique identifier for this graph run, shared with LangSmith metadata."""

    session_id: str
    """Stable client-provided identifier for the conversation session."""

    tracer: Tracer
    """Structured-log emitter; every node calls ``state["tracer"].log(...)``."""
